PROGRAM ZSTATE_REGION.

TABLES: ZTSTATE_REGION.

TYPES: BEGIN OF LTY_DATA,
        REGION TYPE ZDEREGION,
       END OF LTY_DATA.

DATA: LT_DATA TYPE TABLE OF LTY_DATA,
      LWA_DATA TYPE LTY_DATA.


INCLUDE zstate_region_user_command_i01.

INCLUDE zstate_region_status_0100o01.
