PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'ZORDER_TC'
  MODULE ZORDER_TC_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZORDER_TC_CHANGE_COL_ATTR.
  LOOP AT   LT_DATA
       INTO LS_DATA1
       WITH CONTROL ZORDER_TC
       CURSOR ZORDER_TC-CURRENT_LINE.
    MODULE ZORDER_TC_GET_LINES.
*&SPWIZARD:   MODULE ZORDER_TC_CHANGE_FIELD_ATTR
  ENDLOOP.

MODULE STATUS_0200.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'ZORDER_TC'
  LOOP AT LT_DATA.
    CHAIN.
      FIELD LS_DATA1-ONO.
      FIELD LS_DATA1-OIN.
      FIELD LS_DATA1-ODESC.
      FIELD LS_DATA1-ICOST.
    endchain.
  ENDLOOP.
  MODULE ZORDER_TC_USER_COMMAND.
*&SPWIZARD: MODULE ZORDER_TC_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZORDER_TC_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0200.
