PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'ZTC_PRG1'
  MODULE ZTC_PRG1_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZTC_PRG1_CHANGE_COL_ATTR.
  LOOP AT   LT_DATA1
       INTO LWA_DATA1
       WITH CONTROL ZTC_PRG1
       CURSOR ZTC_PRG1-CURRENT_LINE.
    MODULE ZTC_PRG1_GET_LINES.
*&SPWIZARD:   MODULE ZTC_PRG1_CHANGE_FIELD_ATTR
  ENDLOOP.

 MODULE STATUS_0200.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'ZTC_PRG1'
  LOOP AT LT_DATA1.
    CHAIN.
      FIELD LWA_DATA1-ONO.
      FIELD LWA_DATA1-OIN.
      FIELD LWA_DATA1-ODESC.
      FIELD LWA_DATA1-ICOST.
    endchain.
  ENDLOOP.
  MODULE ZTC_PRG1_USER_COMMAND.
*&SPWIZARD: MODULE ZTC_PRG1_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZTC_PRG1_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0200.

*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_0200  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE USER_COMMAND_0200 INPUT.
CALL SCREEN '0100'.
ENDMODULE.
